// Base de Conhecimento Wurm Online - Categorias, Significados e Traduções
const WURM_ACHIEVEMENTS_DB = {
  "Nomad": {
    ptName: "Nômade",
    category: "exploration",
    categoryLabel: "Exploração",
    categoryIcon: "🧭",
    meaning: "Viajante incansável. Concedida por descobrir e visitar vilarejos e assentamentos (deeds) distintos espalhados pelo mapa.",
    unlock: "Caminhe ou navegue até entrar nas fronteiras de diferentes assentamentos (deeds).",
    trivia: "O contador registra quantas vilas diferentes você já explorou! Raro nível Ouro.",
    rarity: "Gold"
  },
  "Epic Helper": {
    ptName: "Ajudante Épico",
    category: "epic",
    categoryLabel: "Missões Épicas",
    categoryIcon: "⚡",
    meaning: "Contribuidor dos deuses. Ajuda valiosa nas missões divinas no cenário de Valrei / Servidor Épico.",
    unlock: "Construa estruturas, sacrifique itens solicitados pelas divindades ou entregue recursos nas missões épicas.",
    trivia: "Valrei é o plano celestial onde as divindades (Fo, Magranon, Vynora, Libila) disputam influência.",
    rarity: "Normal"
  },
  "Epic Finalizer": {
    ptName: "Finalizador Épico",
    category: "epic",
    categoryLabel: "Missões Épicas",
    categoryIcon: "⚡",
    meaning: "Conquistador do passo final. Você realizou a entrega ou ação que encerrou com vitória uma missão épica.",
    unlock: "Dar o último golpe, entregar a última carga de itens ou concluir a última etapa da missão do cenário.",
    trivia: "Dá grande prestígio perante as divindades e seu reino.",
    rarity: "Normal"
  },
  "Knarr Sailor": {
    ptName: "Comandante de Knarr",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "Navegador de Knarr. O Knarr é o navio cargueiro nórdico de médio porte mais popular e versátil do jogo.",
    unlock: "Embarcar no comando (commander) de um navio Knarr e manobrar pelas águas.",
    trivia: "Os vikings usavam o Knarr para viagens oceânicas na Islândia e Groenlândia.",
    rarity: "Normal"
  },
  "Corbita Sailor": {
    ptName: "Comandante de Corbita",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "Navegador mercante de Corbita. Navio comercial clássico do Mediterrâneo com grande porão de carga.",
    unlock: "Embarcar como comandante de uma Corbita.",
    trivia: "A Corbita romana era o verdadeiro caminhão de carga marítimo da antiguidade.",
    rarity: "Normal"
  },
  "Caravel Sailor": {
    ptName: "Comandante de Caravela",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "Capitão de Caravela. Embarcação rápida, de alto nível, excelente para longas jornadas e águas abertas.",
    unlock: "Embarcar como capitão em uma Caravela.",
    trivia: "O tipo de navio histórico usado nas navegações portuguesas e espanholas.",
    rarity: "Normal"
  },
  "Cog Sailor": {
    ptName: "Comandante de Cog",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "Navegador de Cog. Navio medieval robusto de casco bojudo típico da Liga Hanseática.",
    unlock: "Comandar um navio do tipo Cog.",
    trivia: "Era famoso pela estabilidade em mares revoltos no Mar do Norte.",
    rarity: "Normal"
  },
  "Rowboat Sailor": {
    ptName: "Remador de Barco",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "Primeiros passos náuticos remando em um pequeno barco a remo.",
    unlock: "Embarcar e remar em um Rowboat.",
    trivia: "O primeiro barco que a maioria dos jogadores constrói no início da jornada.",
    rarity: "Normal"
  },
  "Sailboat Sailor": {
    ptName: "Marinheiro de Veleiro",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "Navegador de veleiro individual pequeno.",
    unlock: "Comandar um Sailboat.",
    trivia: "Mais rápido que o barco a remo, ideal para viagens curtas entre ilhas vizinhas.",
    rarity: "Normal"
  },
  "Chief Mate": {
    ptName: "Imediato / Contramestre",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "Lobo do mar experiente ('Yarr Matey'). Embarcou incontáveis vezes como capitão.",
    unlock: "Embarcar em embarcações como comandante um grande número de vezes.",
    trivia: "O termo clássico para o segundo em comando na hierarquia naval.",
    rarity: "Normal"
  },
  "Cap'n": {
    ptName: "Capitão Supremo",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "'Aye aye, Cap'n!' Você comandou com sucesso todos os principais tipos de navios existentes no Wurm.",
    unlock: "Pilotar pelo menos uma vez como comandante: Rowboat, Sailboat, Corbita, Cog, Knarr e Caravel.",
    trivia: "Um dos selos definitivos de domínio marítimo do jogo.",
    rarity: "Normal"
  },
  "Out At Sea": {
    ptName: "Em Alto Mar",
    category: "sailing",
    categoryLabel: "Náutica & Navegação",
    categoryIcon: "⛵",
    meaning: "Você navegou para longe das costas continentais em direção às águas profundas do oceano.",
    unlock: "Navegar a uma certa distância da margem para dentro do mar aberto.",
    trivia: "Cuidado com serpentes marinhas e tubarões em alto mar!",
    rarity: "Normal"
  },
  "Just Killed A Man": {
    ptName: "Acabei de Matar um Homem",
    category: "combat",
    categoryLabel: "Combate & PvP",
    categoryIcon: "⚔️",
    meaning: "Abate de jogador em PvP ou finalização fatal em spar. Homenagem à música Bohemian Rhapsody do Queen.",
    unlock: "Abater com sucesso um outro jogador em servidores PvP ou duelos.",
    trivia: "Letra do Queen: 'Mama, just killed a man, put a gun against his head, pulled my trigger now he\'s dead...'",
    rarity: "Normal"
  },
  "Finish Him!": {
    ptName: "Acabe com Ele!",
    category: "combat",
    categoryLabel: "Combate & PvP",
    categoryIcon: "⚔️",
    meaning: "Golpe finalizador esmagador em combate corpo a corpo. Homenagem ao Mortal Kombat.",
    unlock: "Desferir o golpe de misericórdia fatal em um oponente durante a luta.",
    trivia: "Frase icônica do narrador de Mortal Kombat antes dos Fatalities.",
    rarity: "Normal"
  },
  "Be Gentle Please": {
    ptName: "Seja Gentil, Por Favor",
    category: "combat",
    categoryLabel: "Combate & Treino",
    categoryIcon: "⚔️",
    meaning: "Vitória em treino amistoso (Spar). Você venceu um companheiro num duelo de treino sem inimizades.",
    unlock: "Desafiar outro jogador para sparring (/spar) e vencer o embate.",
    trivia: "Sparring é a forma número 1 de subir Fighting skill sem risco de perder equipamentos.",
    rarity: "Normal"
  },
  "Brother In Spars": {
    ptName: "Irmãos de Espada",
    category: "combat",
    categoryLabel: "Combate & Treino",
    categoryIcon: "⚔️",
    meaning: "Parceiro frequente de treino. Você treina e duela regularmente com aliados.",
    unlock: "Participar de múltiplos treinos de spar amigáveis.",
    trivia: "Trocadilho com a clássica canção 'Brothers In Arms' do Dire Straits.",
    rarity: "Normal"
  },
  "The Lucky One": {
    ptName: "O Sortudo",
    category: "combat",
    categoryLabel: "Combate & Sobrevivência",
    categoryIcon: "🍀",
    meaning: "Sobreviveu a uma batalha brutal estando com a barra de saúde praticamente zerada.",
    unlock: "Terminar um combate ou sair vivo com pouquíssima vida restante.",
    trivia: "O famoso 'ficou com 1 de HP e sobreviveu'.",
    rarity: "Normal"
  },
  "Headsman": {
    ptName: "O Carrasco",
    category: "combat",
    categoryLabel: "Combate & PvP",
    categoryIcon: "⚔️",
    meaning: "Execução limpa com arma pesada cortante de duas mãos (machado grande ou two-handed sword).",
    unlock: "Desferir um golpe letal crítico cortante em um oponente.",
    trivia: "Os carrascos medievais usavam machados de lâmina larga para execuções formais.",
    rarity: "Normal"
  },
  "Axe Kill": {
    ptName: "Abate com Machado",
    category: "combat",
    categoryLabel: "Combate & Caça",
    categoryIcon: "🪓",
    meaning: "Matar um adversário ou criatura utilizando machado de combate ou de corte.",
    unlock: "Derrotar inimigos tendo um machado como arma principal.",
    trivia: "O machado é uma das armas mais populares do jogo pelo dano de impacto cortante.",
    rarity: "Normal"
  },
  "Maul Kill": {
    ptName: "Abate com Marreta",
    category: "combat",
    categoryLabel: "Combate & Caça",
    categoryIcon: "🔨",
    meaning: "Esmagar um inimigo até a morte utilizando uma marreta (Maul).",
    unlock: "Finalizar oponentes utilizando arma de concussão pesada (Maul).",
    trivia: "O dano de maul ignora boa parte da armadura de placas, causando dano interno maciço.",
    rarity: "Normal"
  },
  "Hauler": {
    ptName: "Transportador de Carga",
    category: "work",
    categoryLabel: "Logística & Trabalho",
    categoryIcon: "📦",
    meaning: "Transportador incansável de cargas e carroças pesadas pelo terreno.",
    unlock: "Mover e arrastar cargas pesadas, carretas ou veículos cheios de materiais.",
    trivia: "Todo construtor no Wurm passa horas como Hauler para erguer suas fortalezas!",
    rarity: "Normal"
  },
  "Moved A Mountain": {
    ptName: "Moveu Uma Montanha",
    category: "work",
    categoryLabel: "Logística & Trabalho",
    categoryIcon: "⛰️",
    meaning: "'Você sabe puxar uma carroça!' Puxou uma carroça carregada por mais de 250 tiles contínuos.",
    unlock: "Arrastar uma carroça por 250+ tiles de distância sem soltar.",
    trivia: "Dada a topografia difícil do Wurm, puxar uma carroça pesada morro acima é quase mover uma montanha!",
    rarity: "Normal"
  },
  "Trucker": {
    ptName: "Caminhoneiro",
    category: "mounts",
    categoryLabel: "Condução & Veículos",
    categoryIcon: "🚚",
    meaning: "Condutor de carga pesada. Conduziu uma carroça grande (Large Cart) ou vagão de bois.",
    unlock: "Conduzir um Large Cart puxado por animais ou cavalos.",
    trivia: "No Wurm, o Large Cart é o equivalente medieval de uma carreta de 18 rodas!",
    rarity: "Normal"
  },
  "Joyrider": {
    ptName: "Piloto de Fuga",
    category: "mounts",
    categoryLabel: "Montarias & Velocidade",
    categoryIcon: "🏇",
    meaning: "Andar a toda velocidade montado em um cavalo rápido ou conduzindo uma carruagem.",
    unlock: "Cavalgar em alta velocidade em linha reta por um percurso.",
    trivia: "Gíria em inglês para quem dirige em alta velocidade apenas pela diversão e adrenalina.",
    rarity: "Normal"
  },
  "Rider Of The Apocalypse": {
    ptName: "Cavaleiro do Apocalipse",
    category: "mounts",
    categoryLabel: "Montarias Lendárias",
    categoryIcon: "🔥",
    meaning: "Domador do inferno. Montou e cavalgou sobre um temível Hell Horse (cavalo do submundo).",
    unlock: "Domesticar ou montar num Hell Horse / Pesadelo.",
    trivia: "Hell Horses têm olhos em chamas, cascos de brasa e são montarias raras e temidas.",
    rarity: "Normal"
  },
  "Sore Bottom": {
    ptName: "Fundilhos Doloridos",
    category: "mounts",
    categoryLabel: "Montarias & Jornada",
    categoryIcon: "🐴",
    meaning: "Cavalgar por tempo demais sem descer da sela ('dor no bumbum').",
    unlock: "Passar um longo período contínuo montado em um animal sem apear.",
    trivia: "Mais um dos toques de humor britânico característicos dos criadores do Wurm.",
    rarity: "Normal"
  },
  "Dead End": {
    ptName: "Beco Sem Saída",
    category: "survival",
    categoryLabel: "Sobrevivência & Mortes",
    categoryIcon: "💀",
    meaning: "'Às vezes é difícil sobreviver dirigindo.' Morrer tragicamente enquanto estava no comando de uma carroça.",
    unlock: "Ser atacado e morto por uma criatura ou jogador enquanto pilotava um veículo.",
    trivia: "O perigo clássico de cruzar uma floresta escura num cart e encontrar um troll faminto!",
    rarity: "Normal"
  },
  "Ouch That Hurt": {
    ptName: "Ai, Isso Doeu!",
    category: "survival",
    categoryLabel: "Sobrevivência & Quedas",
    categoryIcon: "🩹",
    meaning: "Você despencou de um penhasco ou desmoronou em uma encosta íngreme sofrendo dano severo de impacto.",
    unlock: "Cair de lugares altos ou tropeçar na escalada e levar dano de queda.",
    trivia: "Com 88 ocorrências no seu histórico, você é um escalador aventureiro que não teme precipícios!",
    rarity: "Normal"
  },
  "Wet Feet": {
    ptName: "Pés Molhados",
    category: "exploration",
    categoryLabel: "Exploração & Água",
    categoryIcon: "🌊",
    meaning: "Você entrou nas águas e começou a nadar pela primeira vez.",
    unlock: "Entrar na água funda o suficiente para começar a nadar.",
    trivia: "Cuidado para não nadar com armadura pesada de placas ou sua stamina zera e você se afoga!",
    rarity: "Normal"
  },
  "Went Up A Hill": {
    ptName: "Subiu a Colina",
    category: "exploration",
    categoryLabel: "Exploração & Montanha",
    categoryIcon: "⛰️",
    meaning: "Subiu e explorou o topo de montanhas íngremes.",
    unlock: "Escalar elevações altas com inclinação acentuada.",
    trivia: "Referência à clássica cantiga infantil inglesa 'Jack and Jill went up the hill...'",
    rarity: "Normal"
  },
  "Wanderer": {
    ptName: "O Andarilho",
    category: "exploration",
    categoryLabel: "Exploração & Viagem",
    categoryIcon: "🥾",
    meaning: "Percorreu longas distâncias cruzando a pé as terras e biomas selvagens.",
    unlock: "Andar a pé cobrindo centenas de tiles pelo terreno selvagem.",
    trivia: "O início da lenda de qualquer explorador no Wurm.",
    rarity: "Normal"
  },
  "Tradesman": {
    ptName: "Comerciante",
    category: "work",
    categoryLabel: "Economia & Comércio",
    categoryIcon: "💰",
    meaning: "Homem de negócios. Realizou transações comerciais com sucesso com outros jogadores.",
    unlock: "Abrir a janela de troca (/trade) e concluir uma negociação de moedas ou itens.",
    trivia: "A economia do Wurm é 100% impulsionada pelos próprios jogadores.",
    rarity: "Normal"
  }
};

// ═══════════════════════════════════════════════════════════════
// WIKI_ACHIEVEMENTS — Lista completa de conquistas do Wurmpedia
// Usada pelo Journal 2.0 para comparar com as conquistas desbloqueadas
// ═══════════════════════════════════════════════════════════════
const WIKI_ACHIEVEMENTS = [
  // ── Conquistas Gerais ──────────────────────────────────────
  { name: "Abstinence", rarity: "Silver", description: "You wouldn't mind something to eat. Really really really.", howTo: "Ficar em jejum (Fasting)." },
  { name: "Adamantine Item", rarity: "Silver", description: "You created an adamantine item.", howTo: "Criar um item de adamantite." },
  { name: "Adulterator", rarity: "Silver", description: "You like wine.", howTo: "Fazer 100 litros de vinho." },
  { name: "Almost impossible", rarity: "Diamond", description: "You've manufactured something really special.", howTo: "Criar um item Fantastic." },
  { name: "Almost as good as an Axe", rarity: "Silver", description: "There's always a way to bring down a tree.", howTo: "Cortar uma árvore madura com algo que não seja um machado." },
  { name: "Ambitious", rarity: "Gold", description: "You're not fooling around. You're doing things!", howTo: "100.000 ações realizadas no total." },
  { name: "Angry Sailor", rarity: "Silver", description: "Beware the Angry Sailor and his Belaying Pin.", howTo: "Desconhecido." },
  { name: "Animal Care", rarity: "Silver", description: "How nice of you to feed your pet.", howTo: "Alimentar qualquer animal." },
  { name: "Arachnophile", rarity: "Silver", description: "You hate spiders.", howTo: "Matar muitas aranhas (número exato desconhecido)." },
  { name: "Ascetic", rarity: "Silver", description: "You are dying from famine.", howTo: "Barra de comida abaixo de 7%." },
  { name: "Ashes to Ashes", rarity: "Silver", description: "Most people avoid lava for good reasons.", howTo: "Morrer em um tile de lava." },
  { name: "Backstabber", rarity: "Silver", description: "What's with everyone turning towards you all the time?", howTo: "Derrotar um oponente enquanto ele está de costas para você." },
  { name: "Baker", rarity: "Silver", description: "You should wear a white cap.", howTo: "Assar 100 pães." },
  { name: "Be Gentle Please", rarity: "Silver", description: "You won a spar, hooray!", howTo: "Vencer um duelo (spar)." },
  { name: "Becalmer", rarity: "Silver", description: "You've killed an angry creature.", howTo: "Matar uma criatura raivosa (angry)." },
  { name: "Bodhisattva", rarity: "Gold", description: "Meditating cleans the mind and elevates your soul.", howTo: "Meditar 2000 vezes." },
  { name: "Brass Item", rarity: "Silver", description: "You created a brass item.", howTo: "Criar um item de bronze dourado (brass)." },
  { name: "Bread Maker", rarity: "Silver", description: "You can bake!", howTo: "Assar pão." },
  { name: "Brilliant!", rarity: "Gold", description: "You've mined a brilliant gem.", howTo: "Minerar uma gema de qualidade 90+." },
  { name: "Bronze Item", rarity: "Silver", description: "You created a bronze item.", howTo: "Criar um item de bronze." },
  { name: "Brother In Spars", rarity: "Silver", description: "You're quite popular to spar against.", howTo: "Participar de vários duelos (spars)." },
  { name: "Bugged Rarity", rarity: "Silver", description: "You were the victim of a weird achievement bug but survived.", howTo: "Melhorar qualquer item antes do bug de raridade ser corrigido." },
  { name: "Bumble Bee", rarity: "Gold", description: "Are you in it for the honey, Honey?", howTo: "Plantar 500 flores." },
  { name: "Burglar", rarity: "Silver", description: "They can't keep you out!", howTo: "Abrir 5 cadeados com lockpick." },
  { name: "Cap'n", rarity: "Silver", description: "Aye aye, Cap'n!", howTo: "Embarcar como comandante em todos os tipos de barco." },
  { name: "Careful Identifier", rarity: "Silver", description: "Care and attention to detail let you identify ancient items.", howTo: "Limpar e identificar completamente 50 fragmentos." },
  { name: "Chief Mate", rarity: "Silver", description: "Yarr Matey!", howTo: "Embarcar em barco como comandante muitas vezes." },
  { name: "Citizen", rarity: "Silver", description: "Congratulations! You've joined your first settlement!", howTo: "Se tornar cidadão de um assentamento." },
  { name: "Cleanup Operation", rarity: "Silver", description: "You are recycling things. Good.", howTo: "Jogar 100 itens no trash heap para decair." },
  { name: "Cleptomaniac", rarity: "Silver", description: "Just... one... more...", howTo: "Abrir 50 cadeados com lockpick." },
  { name: "Clumsy", rarity: "Silver", description: "Try to be more gentle when climbing.", howTo: "Cair 125 vezes e tomar dano." },
  { name: "Concrete Shoes", rarity: "Silver", description: "You've discovered that swimming requires training.", howTo: "Morrer afogado." },
  { name: "Cowboy", rarity: "Silver", description: "Bovine is your thing.", howTo: "Puxar 3 touros enquanto anda a cavalo." },
  { name: "Cyclops", rarity: "Silver", description: "Ouch! The eye!", howTo: "Levar um golpe no rosto." },
  { name: "Dead End", rarity: "Silver", description: "Sometimes it's hard to survive while driving.", howTo: "Morrer enquanto conduz uma carroça." },
  { name: "Death from above", rarity: "Silver", description: "Oops!! That must have hurt!", howTo: "Ser atingido por destroços voadores (catapulta)." },
  { name: "Debt Collector", rarity: "Silver", description: "That's your money!", howTo: "Drenar o upkeep de um assentamento." },
  { name: "Decay Removal Services", rarity: "Gold", description: "You could do this for a living.", howTo: "Reparar 1250 cercas, pisos ou paredes." },
  { name: "Deep Pockets", rarity: "Silver", description: "You can't possibly carry more.", howTo: "Estar sobrecarregado e tentar pegar algo." },
  { name: "Deforestation", rarity: "Silver", description: "There is something with you and trees.", howTo: "Cortar 1000 árvores." },
  { name: "Die by the Rift", rarity: "Silver", description: "You died in the Rift Area.", howTo: "Morrer dentro da área do Rift." },
  { name: "Dough Hands", rarity: "Gold", description: "Ignorance and error are necessary to life, like bread and water.", howTo: "Assar 500 pães." },
  { name: "Drunken Sailor", rarity: "Silver", description: "What shall we do with you?", howTo: "Pilotar um barco enquanto bêbado." },
  { name: "Environment Improval Engineer", rarity: "Silver", description: "You take pride in repairing structures.", howTo: "Reparar 250 cercas, pisos ou paredes." },
  { name: "Enviromental Hero", rarity: "Diamond", description: "You're a hero! You keep the world alive!", howTo: "Jogar 10.000 itens no lixo (trash bin)." },
  { name: "Epic helper", rarity: "Silver", description: "You did your part in helping the gods on Valrei.", howTo: "Contribuir para uma missão épica." },
  { name: "Epic Finalizer", rarity: "Silver", description: "You managed to finish that mission. Good job!", howTo: "Completar uma missão épica." },
  { name: "Exceptional craftsmen", rarity: "Silver", description: "You can do really fine things.", howTo: "Melhorar um item de abaixo de 50 QL para acima de 50 QL." },
  { name: "Experienced", rarity: "Silver", description: "You have been premium for 9 months.", howTo: "Ter 9 meses de premium no total." },
  { name: "Fire Extinguisher", rarity: "Gold", description: "You're the nemesis of Lava creatures.", howTo: "Matar uma certa quantidade de lava spiders." },
  { name: "Flirtatious", rarity: "Silver", description: "Your smiles can melt ice.", howTo: "Usar emote 'flirt' em 10 jogadores únicos." },
  { name: "Fo's Favorite", rarity: "Silver", description: "You start to become popular with the gods of nature.", howTo: "Plantar 1000 árvores." },
  { name: "Foundation Pillar", rarity: "Diamond", description: "You've been premium for 36 months.", howTo: "Ter 36 meses de premium." },
  { name: "Fragmental", rarity: "Silver", description: "The ancients apparently used these tools too, who knew?", howTo: "Recriar uma ferramenta a partir de fragmentos." },
  { name: "Founder", rarity: "Silver", description: "There's nothing like home.", howTo: "Fundar um assentamento (deed)." },
  { name: "Free Hugs", rarity: "Silver", description: "You're the cuddly type.", howTo: "Usar emote 'smile' em outro jogador." },
  { name: "Giant Fish", rarity: "Gold", description: "You caught the rare one.", howTo: "Pescar um tubarão muito pesado e de alta qualidade." },
  { name: "Ghost", rarity: "Silver", description: "Others only notice a slight movement of the air.", howTo: "Usar stealth com sucesso 200 vezes." },
  { name: "Ghost of the Rift Warmasters", rarity: "Gold", description: "You're scaring the Rift Warmasters.", howTo: "Desconhecido." },
  { name: "Glittered", rarity: "Gold", description: "You've been premium for 20 months.", howTo: "Ter 20 meses de premium." },
  { name: "Gold Digger", rarity: "Silver", description: "Found the Gold. Now - what to do with it?", howTo: "Minerar ouro." },
  { name: "Gollum", rarity: "Silver", description: "It came to me, my own, my love... my... preciousss.", howTo: "Usar stealth em uma caverna com um anel equipado." },
  { name: "Gravedigger", rarity: "Silver", description: "You put the dead to rest.", howTo: "Enterrar um cadáver." },
  { name: "Good Work", rarity: "Silver", description: "You excel in improving things.", howTo: "Melhorar um item para QL acima da sua habilidade." },
  { name: "Hauler", rarity: "Silver", description: "You've worked hard today.", howTo: "Arrastar uma carroça por 250 tiles." },
  { name: "Hedgehog", rarity: "Silver", description: "You are a one for hedges.", howTo: "Plantar 200 cercas vivas ou canteiros." },
  { name: "Hexer", rarity: "Silver", description: "Are you addicted to potions?", howTo: "Beber 20 poções." },
  { name: "Highly Illuminated", rarity: "Gold", description: "You've been premium for 26 months.", howTo: "Ter 26 meses de premium." },
  { name: "Hippie", rarity: "Silver", description: "Flower power!", howTo: "Plantar 100 flores." },
  { name: "Horse Whisperer", rarity: "Silver", description: "You communicate with them.", howTo: "Usar emote 'wave' em um cavalo." },
  { name: "Improve", rarity: "Silver", description: "There! That makes it better.", howTo: "Melhorar um item com sucesso." },
  { name: "In The Name of Magranon", rarity: "Silver", description: "Making those swords pleases certain deities.", howTo: "Desconhecido." },
  { name: "Investigating the Rift", rarity: "Silver", description: "What's up there?", howTo: "Cruzar o tile central de uma área de Rift antes de ele abrir." },
  { name: "If Looks Could Kill", rarity: "Silver", description: "Supposedly if you dye them red, you'll move faster.", howTo: "Tingir uma peça de armadura." },
  { name: "Irresponsible Driving", rarity: "Silver", description: "Haven't you heard? Don't drink and drive!", howTo: "Embarcar em uma carroça como motorista enquanto bêbado." },
  { name: "Janitor", rarity: "Silver", description: "You keep the place in good order.", howTo: "Reparar 50 cercas, pisos ou paredes." },
  { name: "Just a Cold", rarity: "Silver", description: "Sniffle. You've got a cold.", howTo: "Ficar doente (diseased)." },
  { name: "Johnny Appleseed", rarity: "Gold", description: "You have to check your skin for bark complexion.", howTo: "Plantar 5.000 árvores." },
  { name: "Joyrider", rarity: "Silver", description: "You had the chance to view the surroundings quite a while there.", howTo: "Andar 4000 tiles em uma carroça como passageiro." },
  { name: "Knarr Sailor", rarity: "Silver", description: "Look, it floats!", howTo: "Comandar um Knarr." },
  { name: "King's court", rarity: "Gold", description: "You have been allowed to join the Inner ranks.", howTo: "Ter um cargo no reino." },
  { name: "Landed", rarity: "Silver", description: "You have been premium for 1 month.", howTo: "Ter 1 mês de premium." },
  { name: "Last Rope", rarity: "Silver", description: "The more the merrier.", howTo: "Puxar 3 animais ao mesmo tempo." },
  { name: "Longterm Attachments", rarity: "Gold", description: "?", howTo: "Desconhecido." },
  { name: "Marble Bridge Maker", rarity: "Silver", description: "You finished a Marble Bridge.", howTo: "Completar uma ponte de mármore." },
  { name: "Master Bridgebuilder", rarity: "Gold", description: "People should come to you for bridges.", howTo: "Completar uma ponte de cada tipo de material." },
  { name: "Master Winemaker", rarity: "Diamond", description: "Winemaking is an art, and you're an expert at it!", howTo: "Fazer 5000 litros de vinho." },
  { name: "Master of Recreation", rarity: "Gold", description: "Just like pieces of a puzzle.", howTo: "Recriar múltiplos itens através de arqueologia." },
  { name: "Master of Runes", rarity: "Gold", description: "Just a few more bonuses.", howTo: "Desconhecido." },
  { name: "Mountain Goat", rarity: "Silver", description: "Wow, you can really climb heights.", howTo: "Subir a uma altitude maior que 'Went up a Hill'." },
  { name: "Moved a Mountain", rarity: "Silver", description: "You know how to drag a cart.", howTo: "Desconhecido." },
  { name: "Miner on Strike", rarity: "Silver", description: "Better not to underestimate a miner and his pickaxe.", howTo: "Matar outro jogador usando uma picareta." },
  { name: "Myth Or Legend?", rarity: "Diamond", description: "You have been premium for 80 months.", howTo: "Ter 80 meses de premium." },
  { name: "Nomad", rarity: "Gold", description: "Are you restless?", howTo: "Viajar uma distância muito longa (10x 'Wanderer')." },
  { name: "Nancy the Tavern Wench", rarity: "Silver", description: "Let's dance!", howTo: "Dançar com 10 jogadores únicos usando emote." },
  { name: "Obsessive Eater", rarity: "Silver", description: "Welp, don't have any space left now. *BURP*", howTo: "Comer até 99% de saciedade." },
  { name: "On the Way to the Moon", rarity: "Silver", description: "There's no limit! No, no, no limit!", howTo: "Subir ainda mais alto que 'Thin Air'." },
  { name: "On the path to perfection", rarity: "Gold", description: "You are soon at the highest level of creation.", howTo: "Melhorar um item de abaixo de 90 QL para acima de 90 QL." },
  { name: "Oops, That Went Wrong", rarity: "Silver", description: "Hope it didn't break.", howTo: "Falhar ao melhorar um item." },
  { name: "Ouch That Hurt", rarity: "Silver", description: "(no description)", howTo: "Cair de uma altura e se machucar." },
  { name: "Out At Sea", rarity: "Silver", description: "Hope you're not out of your depth.", howTo: "Navegar em águas profundas." },
  { name: "Overdosed on Acupuncture", rarity: "Silver", description: "Those thorns give deadly prickles.", howTo: "Morrer por causa de espinhos (thorns) ou barreiras de ponta." },
  { name: "Own the Rift", rarity: "Diamond", description: "You've defeated an insane amount of Rift Creatures.", howTo: "Matar um número enorme de criaturas do Rift." },
  { name: "Owning", rarity: "Gold", description: "You've been premium 12 months.", howTo: "Ter 12 meses de premium." },
  { name: "Patron Of The Net", rarity: "Diamond", description: "You have been premium for 60 months.", howTo: "Ter 60 meses de premium." },
  { name: "Peace of Mind", rarity: "Silver", description: "You are getting in to not getting in to things.", howTo: "Meditar 200 vezes." },
  { name: "Paul Bunyan", rarity: "Silver", description: "You can measure yourself with the greatest of lumberjacks.", howTo: "Cortar 5000 árvores." },
  { name: "Peasant Winemaker", rarity: "Silver", description: "You really like wine!", howTo: "Fazer 500 litros de vinho." },
  { name: "Perfection", rarity: "Diamond", description: "Few have mastered item creation like you.", howTo: "Criar um item de qualidade 99." },
  { name: "Pizza Master", rarity: "Silver", description: "Pizza is amazing.", howTo: "Fazer uma quantidade enorme de pizza." },
  { name: "Popular Joe", rarity: "Silver", description: "You have many friends!", howTo: "Adicionar 50 pessoas à lista de amigos." },
  { name: "Pursuit of excellence", rarity: "Silver", description: "You manage to improve yourself.", howTo: "Melhorar um item de abaixo de 70 QL para acima de 70 QL." },
  { name: "Rarity", rarity: "Silver", description: "You crafted something which is better than everything there ever was before.", howTo: "Melhorar um item passando o máximo anterior do servidor." },
  { name: "Rarity Discovered", rarity: "Silver", description: "You have no trouble finding the best secrets of the past.", howTo: "Encontrar um fragmento raro." },
  { name: "Really rare", rarity: "Silver", description: "You've manufactured a really rare item.", howTo: "Criar itens raros." },
  { name: "Revered one", rarity: "Diamond", description: "You have been premium for 48 months.", howTo: "Ter 48 meses consecutivos de premium." },
  { name: "Rift Specialist", rarity: "Gold", description: "You've defeated all sorts of Rift creatures.", howTo: "Matar criaturas do Rift." },
  { name: "Rift Opener", rarity: "Silver", description: "You sacrificed at the Rift Altar.", howTo: "Sacrificar um coração de Rift no altar do Rift." },
  { name: "Rider of the Apocalypse", rarity: "Silver", description: "You rode, and rode, and rode.", howTo: "Viajar ~16km a cavalo dentro de 1 hora de login." },
  { name: "Rope Bridge Maker", rarity: "Silver", description: "You finished a Rope Bridge.", howTo: "Completar uma ponte de corda." },
  { name: "Ruler", rarity: "Diamond", description: "You made it to the top.", howTo: "Tornar-se líder de facção em Elevation ou Chaos." },
  { name: "Sandwich Maker", rarity: "Silver", description: "As the Sandwich-Islander believes that the strength of the enemy passes into himself...", howTo: "Fazer um sanduíche." },
  { name: "Scouted", rarity: "Silver", description: "You have been premium for 6 months.", howTo: "Ter 6 meses de premium." },
  { name: "Settlement assault", rarity: "Silver", description: "You've killed an enemy spirit guard.", howTo: "Matar um guarda espiritual inimigo." },
  { name: "Settler", rarity: "Silver", description: "A house is like a heart just bigger.", howTo: "Finalizar uma casa (completar a última parede)." },
  { name: "Shadow", rarity: "Silver", description: "Hiding in the shadows is becoming one of your favorite pastimes.", howTo: "Usar stealth com sucesso 50 vezes." },
  { name: "Shaking the Foundations of the Earth", rarity: "Silver", description: "Shake them orbs!", howTo: "Colapsar 5 entradas de mina usando shaker orbs." },
  { name: "Shutting Down", rarity: "Silver", description: "You were there when the Rift was shut.", howTo: "Participar de um Rift e estar online quando ele fechar." },
  { name: "Slacker", rarity: "Silver", description: "You're just standing there!", howTo: "Desconhecido." },
  { name: "Sneaky", rarity: "Silver", description: "Sometimes it is best not to be seen by others.", howTo: "Usar stealth com sucesso 10 vezes." },
  { name: "Singing While Eating", rarity: "Silver", description: "Who was that cook?", howTo: "Comer comida de alta qualidade." },
  { name: "Sisyphus Says Hello", rarity: "Diamond", description: "Is this boring yet?", howTo: "Reparar 6250 cercas, pisos ou paredes." },
  { name: "Skilled", rarity: "Silver", description: "Skill points. Can't have too many of them.", howTo: "Certa quantidade de pontos de habilidade totais." },
  { name: "Sore Bottom", rarity: "Silver", description: "Ok that horse got me pretty far, now where's my farmer's salve.", howTo: "Montar por muito tempo." },
  { name: "Speed Fighter", rarity: "Silver", description: "You've killed an alert creature.", howTo: "Matar uma criatura alert." },
  { name: "Statue Bro?", rarity: "Gold", description: "A really big puzzle with a lot of pieces - easy.", howTo: "Recriar uma estátua a partir de fragmentos." },
  { name: "Stone Bridge Maker", rarity: "Silver", description: "You finished a Stone Bridge.", howTo: "Completar uma ponte de pedra." },
  { name: "Supreme being", rarity: "Gold", description: "You've created a supreme item.", howTo: "Criar um item supreme." },
  { name: "Survived", rarity: "Silver", description: "You have been premium for 3 months.", howTo: "Ter 3 meses de premium consecutivos." },
  { name: "Talented Investigator", rarity: "Silver", description: "The ancient world cannot hide any secrets from you!", howTo: "Investigar e encontrar 50 fragmentos." },
  { name: "The First", rarity: "Silver", description: "You're all alone here!", howTo: "Ser o primeiro em um servidor." },
  { name: "The Lucky One", rarity: "Silver", description: "Wow, that was really, really close.", howTo: "Se curar de menos de 1% de vida." },
  { name: "The Path of Vynora", rarity: "Gold", description: "You and fishing are one.", howTo: "Pescar 1.000 peixes." },
  { name: "The Smell of Freshly Baked Bread", rarity: "Silver", description: "If you have two loaves of bread, sell one and buy a lily.", howTo: "Assar 100 pães." },
  { name: "Thin Air", rarity: "Silver", description: "How high can you reach?", howTo: "Subir mais alto que 'Mountain Goat'." },
  { name: "Tossed Dwarf", rarity: "Silver", description: "Nobody dares to throw you around.", howTo: "Ser arremessado." },
  { name: "Tower Builder", rarity: "Silver", description: "You finished the guard tower.", howTo: "Construir uma torre de guarda." },
  { name: "Tradesman", rarity: "Silver", description: "You're seeing the world!", howTo: "Viajar entre servidores." },
  { name: "Tree Hugger", rarity: "Silver", description: "You plant trees.", howTo: "Plantar 200 brotos (sprouts) com sucesso." },
  { name: "Trucker", rarity: "Silver", description: "You drove that cart really far.", howTo: "Dirigir uma carroça como comandante por muito tempo." },
  { name: "Truffle Pig", rarity: "Silver", description: "You like them mushies.", howTo: "Colher 20 cogumelos." },
  { name: "Undertaker", rarity: "Silver", description: "You keep souls to rest and the world free from rotting corpses.", howTo: "Enterrar 100 cadáveres." },
  { name: "Under the Influence", rarity: "Silver", description: "You like them potions.", howTo: "Beber 5 poções." },
  { name: "Up The Drain", rarity: "Silver", description: "You've got expenses like everyone else!", howTo: "Drenar um assentamento 2 dias seguidos." },
  { name: "Vigneron", rarity: "Gold", description: "Creating wine is your thing.", howTo: "Fazer 1000 litros de vinho." },
  { name: "Vynora commands you", rarity: "Silver", description: "The fish bring secrets from the deep.", howTo: "Pescar 200 peixes." },
  { name: "Waller", rarity: "Silver", description: "You weaved the source and created a wall.", howTo: "Conjurar uma parede mágica." },
  { name: "Wanderer", rarity: "Silver", description: "You know how to move around.", howTo: "Viajar uma longa distância." },
  { name: "Warrior", rarity: "Gold", description: "You're getting a reputation for being a successful fighter.", howTo: "Alcançar 1100 de Battle Rank." },
  { name: "Well Maker", rarity: "Silver", description: "You found water and brought it to the surface of the world.", howTo: "Construir um poço em um tile com fonte de água." },
  { name: "Went up a Hill", rarity: "Silver", description: "The view is pretty up here.", howTo: "Subir a uma altitude elevada." },
  { name: "Wet Feet", rarity: "Silver", description: "It's cold. It's wet. I don't like it.", howTo: "Entrar na água." },
  { name: "Won The Game", rarity: "Diamond", description: "You achieved all your personal goals in these lands.", howTo: "Completar todos os seus objetivos pessoais (Goals)." },
  { name: "Wooden Bridge Maker", rarity: "Silver", description: "You finished a Wooden Bridge.", howTo: "Completar uma ponte de madeira." },
  { name: "You Beauty", rarity: "Silver", description: "You like to dress up.", howTo: "Usar anel, colar e pulseira ao mesmo tempo." },
  // ── Kill Counters ──────────────────────────────────────────
  { name: "All Hell", rarity: "Gold", description: "You've held your ground against the Hell creatures.", howTo: "Matar um de cada: Hell Scorpious, Hell Horse e Hell Hound." },
  { name: "Axe Kill", rarity: "Silver", description: "Count of players killed with any type of axe.", howTo: "Matar um jogador com qualquer tipo de machado." },
  { name: "Bear Hunt", rarity: "Silver", description: "You've killed the bear.", howTo: "Matar um urso." },
  { name: "Bisons", rarity: "Silver", description: "You've killed the bison.", howTo: "Matar um bisão." },
  { name: "Bovine Master", rarity: "Silver", description: "You slay bovine like none other.", howTo: "Matar uma vaca." },
  { name: "Braaains", rarity: "Silver", description: "Zombies stand no chance.", howTo: "Matar 10 zumbis." },
  { name: "Crocodile Dundee", rarity: "Gold", description: "It was the croc and not you this time.", howTo: "Matar um grande número de crocodilos." },
  { name: "Crocodiles Killed", rarity: "Silver", description: "You need them shoes, belts and bags.", howTo: "Matar um crocodilo." },
  { name: "Dances with Wolves", rarity: "Silver", description: "You know how to kill wolves now.", howTo: "Matar 100 lobos." },
  { name: "Death comes Crawling", rarity: "Silver", description: "You've killed the Deathcrawler.", howTo: "Matar um Deathcrawler Minion." },
  { name: "Debugger", rarity: "Silver", description: "You've killed the bug. Thank you.", howTo: "Matar um cave bug." },
  { name: "Deer Killed", rarity: "Silver", description: "You've killed the dear.", howTo: "Matar um cervo." },
  { name: "Demons", rarity: "Silver", description: "You've killed the demon.", howTo: "Matar um Sol Demon." },
  { name: "Dog Life", rarity: "Silver", description: "You put dogs out of their misery.", howTo: "Matar um cachorro." },
  { name: "Dragonslayer", rarity: "Gold", description: "You've killed the Dragon.", howTo: "Estar em combate com um dragão quando ele morrer." },
  { name: "Drakeslayer", rarity: "Gold", description: "You've killed a Drake.", howTo: "Estar em combate com um filhote de dragão quando ele morrer." },
  { name: "Drake Spirits", rarity: "Silver", description: "You've killed the Drake Spirit.", howTo: "Matar um Drakespirit." },
  { name: "Goblin Slayer", rarity: "Silver", description: "You've killed the goblin.", howTo: "Matar um goblin." },
  { name: "Hello Goodbye", rarity: "Silver", description: "You've killed the Hell Scorpius.", howTo: "Matar um Hell Scorpious." },
  { name: "Hellova fight", rarity: "Silver", description: "You've killed Hell Horse.", howTo: "Matar um Hell Horse." },
  { name: "Honey, guess what's for dinner!", rarity: "Gold", description: "Too many spiders!", howTo: "Matar 1000 aranhas." },
  { name: "How many Sons?", rarity: "Silver", description: "You've killed the Son of Nogump.", howTo: "Matar um Son of Nogump." },
  { name: "Hunter Apprentice", rarity: "Silver", description: "Deers are easy to hunt.", howTo: "Matar 20 cervos." },
  { name: "Incarnated To Hell", rarity: "Gold", description: "You've vanquished the Incarnation of Libila.", howTo: "Matar um Avatar de Libila." },
  { name: "Kill the pig", rarity: "Silver", description: "You require pork.", howTo: "Matar um porco." },
  { name: "Kingdom Infiltration", rarity: "Silver", description: "You've killed an enemy kingdom creature.", howTo: "Matar uma criatura do reino inimigo." },
  { name: "Lava Fiends Killed", rarity: "Silver", description: "You've killed the lava fiend.", howTo: "Matar um lava fiend." },
  { name: "Lava Spiders Killed", rarity: "Silver", description: "You've killed the lava spider.", howTo: "Matar uma lava spider." },
  { name: "Meoww!", rarity: "Silver", description: "Wild Cats try to put up a fight.", howTo: "Matar um gato selvagem." },
  { name: "Mercykiller", rarity: "Silver", description: "You've killed a diseased creature.", howTo: "Matar um animal doente (diseased)." },
  { name: "Moby Dick", rarity: "Silver", description: "You've killed the Huge Shark.", howTo: "Matar um Huge Shark." },
  { name: "My furry eight-legged friends", rarity: "Diamond", description: "What's up with these spiders everywhere?", howTo: "Matar 2000 aranhas." },
  { name: "No Fuel for the Flame of Udun", rarity: "Gold", description: "", howTo: "Matar 100 lava fiends." },
  { name: "No Son of a Troll", rarity: "Gold", description: "You don't fancy trolls.", howTo: "Matar 1000 trolls." },
  { name: "Off Horse", rarity: "Silver", description: "You slay horses.", howTo: "Matar um cavalo." },
  { name: "One Eyed Snake", rarity: "Gold", description: "You've killed the Kyklops.", howTo: "Estar em combate com o Kyklops quando ele morrer." },
  { name: "Out, out, brief candle!", rarity: "Silver", description: "It appears scaring hens to death is your favorite pasttime.", howTo: "Matar dez galinhas." },
  { name: "Pheasant Hunt", rarity: "Silver", description: "You've killed the pheasant.", howTo: "Matar um faisão." },
  { name: "Rat Race", rarity: "Silver", description: "The rat race has begun!", howTo: "Matar um rato." },
  { name: "Rift Beasts", rarity: "Silver", description: "You've vanquished a Rift Beast.", howTo: "Matar um Rift Beast." },
  { name: "Rift Jackals", rarity: "Silver", description: "You've vanquished a Rift Jackal!", howTo: "Matar um Rift Jackal." },
  { name: "Rift Ogre", rarity: "Silver", description: "You've vanquished a Rift Ogre.", howTo: "Matar um Rift Ogre." },
  { name: "Rift Warmaster", rarity: "Silver", description: "You've vanquished a Rift Warmaster.", howTo: "Matar um Rift Warmaster." },
  { name: "Rrreoww!", rarity: "Silver", description: "Mountain Lions try to put up a fight.", howTo: "Matar um leão da montanha." },
  { name: "Scrapion", rarity: "Silver", description: "Scorpions are at your mercy.", howTo: "Matar um escorpião." },
  { name: "Sea Mastership", rarity: "Silver", description: "You've killed the Sea Serpent.", howTo: "Matar uma serpente do mar." },
  { name: "Settlement Assault", rarity: "Silver", description: "You've killed an enemy spirit guard.", howTo: "Matar um Spirit Templar inimigo." },
  { name: "Silencer", rarity: "Silver", description: "You've killed a raging creature.", howTo: "Matar uma criatura raging." },
  { name: "Slayer of Procastination", rarity: "Silver", description: "You've killed a slow creature.", howTo: "Matar uma criatura slow." },
  { name: "Slayer of the Champ", rarity: "Silver", description: "You've killed a champion creature.", howTo: "Matar uma criatura champion." },
  { name: "Slayer of the Fiercity", rarity: "Silver", description: "You've killed a fierce creature.", howTo: "Matar uma criatura fierce." },
  { name: "Slayer of The Lurker", rarity: "Silver", description: "You've killed a lurking creature.", howTo: "Matar uma criatura lurking." },
  { name: "Slayer of the Meek", rarity: "Silver", description: "You've killed a scared creature.", howTo: "Matar uma criatura scared." },
  { name: "Slayer of the Sly", rarity: "Silver", description: "You've killed a sly creature.", howTo: "Matar uma criatura sly." },
  { name: "Soilent Green", rarity: "Silver", description: "You've killed a greenish creature.", howTo: "Matar uma criatura greenish." },
  { name: "Speedfighter", rarity: "Silver", description: "You've killed an alert creature.", howTo: "Matar uma criatura alert." },
  { name: "Spiders Killed", rarity: "Silver", description: "You've killed a spider.", howTo: "Matar uma aranha." },
  { name: "Tastes like Chicken", rarity: "Silver", description: "You know how to get crocodile meat.", howTo: "Matar 20 crocodilos." },
  { name: "Tears of the Unicorn", rarity: "Silver", description: "You are a slayer of beauty.", howTo: "Matar 100 unicórnios." },
  { name: "To hell with it", rarity: "Silver", description: "You've killed the Hell Hound.", howTo: "Matar um Hell Hound." },
  { name: "Traitor", rarity: "Silver", description: "And that poor guard was just doing his duty.", howTo: "Matar um guarda (guard)." },
  { name: "Troll King Assassination", rarity: "Gold", description: "You've killed the Troll King.", howTo: "Estar em combate com o Troll King quando ele morrer." },
  { name: "Trolls killed", rarity: "Silver", description: "You've killed the fearsome Troll.", howTo: "Matar um troll." },
  { name: "Unicorns Killed", rarity: "Silver", description: "You've slain the Unicorn.", howTo: "Matar um unicórnio." },
  { name: "Uttacha Spawn Slayer", rarity: "Silver", description: "You've killed the Uttacha Spawn.", howTo: "Matar um Spawn of Uttacha." },
  { name: "Willbreaker", rarity: "Silver", description: "You've killed a hardened creature.", howTo: "Matar uma criatura hardened." },
  { name: "Wolves killed", rarity: "Silver", description: "You're a wolf slayer.", howTo: "Matar um lobo." },
  { name: "You Cannot Pass", rarity: "Silver", description: "You have defeated many Lava Fiends.", howTo: "Matar 20 lava fiends." },
  { name: "Zombies killed", rarity: "Silver", description: "Zombie! Zombie!", howTo: "Matar um zumbi." },
  { name: "Zombie Hunter", rarity: "Gold", description: "Apparently It's you or zombies.", howTo: "Matar 50 zumbis." },
  // ── Culinária ─────────────────────────────────────────────
  { name: "Beer", rarity: "Silver", description: "Homebrew!", howTo: "Fermentar cerveja." },
  { name: "Berry Pie", rarity: "Silver", description: "Berry nice!", howTo: "Assar uma torta de frutas vermelhas." },
  { name: "Black Forest Gateau", rarity: "Silver", description: "I want to get lost in this forest!", howTo: "Assar um Black Forest Gateau." },
  { name: "Brewer", rarity: "Silver", description: "Brewed one of each.", howTo: "Fermentar um de cada tipo de bebida." },
  { name: "Chocoholic", rarity: "Silver", description: "um, chocolate!", howTo: "Assar um bolo de chocolate." },
  { name: "Cookies", rarity: "Silver", description: "You say cookie, I say biscuit, lets om-nom-nom.", howTo: "Assar biscoitos." },
  { name: "Cottage Pie", rarity: "Silver", description: "Just like my grandmother used to make!", howTo: "Assar uma Cottage Pie." },
  { name: "Custard Creams", rarity: "Silver", description: "When only the cream de la cream will do!", howTo: "Assar Custard Creams." },
  { name: "Custard Pie", rarity: "Silver", description: "Phanton flam flinger.", howTo: "Assar uma Custard Pie." },
  { name: "Distiller", rarity: "Silver", description: "Distilled one of each!", howTo: "Destilar um de cada tipo de álcool." },
  { name: "Fish pie", rarity: "Silver", description: "You made that, sounds a bit fishy to me!", howTo: "Cozinhar uma torta de peixe." },
  { name: "Fruit Pie", rarity: "Silver", description: "Berry nice!", howTo: "Assar uma torta de frutas." },
  { name: "Gin", rarity: "Silver", description: "As drunk on fine floating palaces everywhere.", howTo: "Destilar gin." },
  { name: "Gruel", rarity: "Silver", description: "Please sir, can I have some more?", howTo: "Cozinhar mingau (gruel)." },
  { name: "Insect Stew", rarity: "Silver", description: "You begin to feel the speed of 6 legs come upon you.", howTo: "Cozinhar ensopado de insetos." },
  { name: "Meat pie", rarity: "Silver", description: "Meat and gravy all in a pie!", howTo: "Assar uma torta de carne." },
  { name: "Moonshine", rarity: "Silver", description: "Yeee-haw!", howTo: "Destilar moonshine." },
  { name: "Pasta Maker", rarity: "Silver", description: "Life is a combination of magic and pasta.", howTo: "Desconhecido." },
  { name: "Pie-Maker", rarity: "Silver", description: "When you die, if you get a choice between going to regular heaven and pie heaven, choose pie heaven.", howTo: "Fazer um de cada tipo de torta: Cottage, fish, raspberry, fruit, berry, custard, steak and ale, pork e meat." },
  { name: "Pizza Maker", rarity: "Silver", description: "Making the world a better place, one tomato-laden delight at a time.", howTo: "Desconhecido." },
  { name: "Pork pie", rarity: "Silver", description: "Come here, piggy!", howTo: "Assar uma Pork Pie." },
  { name: "Raspberry Pi", rarity: "Silver", description: "The code for this was intense!", howTo: "Assar uma Raspberry Pi." },
  { name: "Simple pasta", rarity: "Silver", description: "I make a pasta!", howTo: "Cozinhar massa simples." },
  { name: "Steak and ale pie", rarity: "Silver", description: "um, beer!", howTo: "Assar uma Steak and Ale Pie." },
  { name: "Sushi Maker", rarity: "Silver", description: "Teach a man to fish, but not cook, and he'll make sushi.", howTo: "Fazer sushi." },
  { name: "Vinegar", rarity: "Silver", description: "Oops, that was not expected, maybe I can use it for cooking!", howTo: "Fazer vinagre." },
  { name: "Vodka", rarity: "Silver", description: "At least one letter away from water.", howTo: "Destilar vodka." },
  { name: "Whisky", rarity: "Silver", description: "Always carry a small flask of whiskey in case of snake bite.", howTo: "Destilar whisky." },
  // ── Eventos ───────────────────────────────────────────────
  { name: "Independence Tourist", rarity: "Iron", description: "You've toured the sights of Independence!", howTo: "Completar a Corrida Turística de Independence." },
  { name: "Gopher for the Gods", rarity: "Iron", description: "You finished the May 2016 Scavenger hunt.", howTo: "Completar o Treasure Hunt de maio de 2016 em Independence." },
  { name: "Geographer of the Isles", rarity: "Iron", description: "You have successfully pieced together the locations to a treasure map.", howTo: "Completar o evento de abril de 2016 em Pristine." },
  { name: "I survived the Labyrinth.", rarity: "Iron", description: "Granted for completing the 2015 Labyrinth on Xanadu.", howTo: "Completar o famoso Labirinto de Xanadu." }
];
